name: Logging
on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/luaver@v1.2.0
        with:
          lua-version: "5.1"

      - name: Run Lua script
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
        run: lua Utility/Webhook.luau
