name: logger
on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/luaver@v1.2.0
        with:
          lua-version: "5.1"

      - name: Run Lua script
        env:
          webhook: ${{ secrets.webhook }}
        run: lua Utility/Webhook.luau
